### ISSUE TITLE
No module named Files

### ISSUE THREAD

**Issue by rleaver152** [SamSamhuns/face_detection_and_recognition#4]
to run 
python data_extraction/extract_and_clean_imdb_wiki_faces.py -d {data/imdb, data/wiki}

1. in the call  "from modules.files import read_pickle, write_json"
there isn't a file called "files' in the "modules" directory   so cannot load modules.files

2. the directory is face_extraction (rather than data_extraction)  :-)

**Comment by SamSamhuns** [comment]
Hi, thanks for pointing these out. I haven't had the time to update the face extraction after I did some refactoring of the face detection modules. It should work now.

Now you can download the imdb-wiki dataset from `https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/`, place a subset of this data inside `data/wiki` and run the extraction script `python face_extraction/extract_and_clean_imdb_wiki_faces.py -d data/wiki`
